---
title: "Census Data Pull"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(tidycensus)
library(plotly)
library(stringr)
library(lubridate)

`%notin%` <- negate(`%in%`)

# census_api_key(api_key, install = TRUE)
# readRenviron("~/.Renviron")
api_key <- "f4c735caedf3cabe35997343d8f5502aa0ca322f"

```


```{r}

# https://api.census.gov/data/key_signup.html. 

url <- "https://api.census.gov/data/2019/acs/acs1?get=NAME,group(B01003)&for=us:1&key="
api_key <- "f4c735caedf3cabe35997343d8f5502aa0ca322f"
my_api <- paste0(url,api_key)
census <- jsonlite::fromJSON(my_api) 
census_transform <- row_to_names(census, 1) %>% as_tibble()
census_transform <- census_transform %>% 
                pivot_longer(!NAME,
                  names_to = "type",
                  values_to = "data"
                )

census_variables <- load_variables(2019, "acs5", cache = TRUE) 
census_variables %>% write_csv("census_variables.csv")

```

```{r}

db_geo_county_state_map <-  fips_codes %>% 
                                mutate(
                                    county_id = paste0(state_code, county_code),
                                ) %>% 
                                select(county_id, county, state)

```


### census_bureau_income
```{r}

### ZCTA State Mapping
url_zcta <- "https://www2.census.gov/geo/docs/maps-data/data/rel/zcta_county_rel_10.txt"
census_zcta <- read_csv(url_zcta) %>% 
                    mutate(
                           STATE = str_pad(STATE, 2, pad = "0"),
                           COUNTY = paste0(STATE, COUNTY)
                           )

zcta_county_mapping <- census_zcta %>%
                          select(ZCTA5, COUNTY) %>% group_by(ZCTA5) %>% slice(1)


hhincome <- get_acs(geography = "zcta", year = 2019, survey = "acs5", 
                         variables = c(medincome ="B19013_001"))


db_census_bureau_income <- hhincome %>% 
                          left_join(zcta_county_mapping, by = c("GEOID"="ZCTA5")) %>% 
                                      mutate(zcta = GEOID,
                                             county_id = COUNTY,
                                             household_median_income =  if_else(is.na(estimate),0,estimate)
                                             )  %>% 
                          select(zcta, county_id, household_median_income)



```

### Census Bureau Population
```{r}

age_population <- load_variables(2019, "acs5", cache = TRUE) %>% 
                        filter(substr(name ,1,7) == "B01001_" & 
                        name %notin% c("B01001_001","B01001_002","B01001_026"))

age_list <- age_population$name
df_age_pop <- as_tibble()

a <- "B01001_003"
for (a in age_list) {
  
  age_pop <- get_acs(geography = "zcta", year = 2019, survey = "acs5", 
                         variables = a)
  
  df_age_pop <- union_all(df_age_pop, age_pop)
  
}

age_mapping <- read_csv("age_mapping.csv")
db_census_bureau_population <- df_age_pop %>% left_join(age_mapping, by = c("variable"="name")) %>% 
                  mutate(zcta = GEOID,
                         age_group = label,
                         population = estimate) %>% 
                  group_by(id_part, zcta, age_group) %>% 
                  summarise(
                            population = sum(population),
                            .groups = "drop"
                            ) %>% 
                  ungroup() %>% 
                  mutate(population_id = paste0(zcta, id_part)) %>% 
                  arrange(zcta, id_part) %>% 
                  select(population_id, zcta, age_group, population)


length(unique(db_census_bureau_population$population_id))
length(db_census_bureau_population$population_id)

```

### Census Bureau House Hold Income By Race
```{r}

mhhi_race <- read_csv("mhhi_mapping.csv")

mhhi_race_list <- mhhi_race$name
df_race_mhhi <- as_tibble()

a <- "B19013A_001"
for (m in mhhi_race_list) {
  
  race_mhhi <- get_acs(geography = "zcta", year = 2019, survey = "acs5", 
                         variables = m)
  
  df_race_mhhi <- union_all(df_race_mhhi, race_mhhi)
  
}



db_census_bureau_mhhi_race <- df_race_mhhi %>% left_join(mhhi_race, by = c("variable"="name")) %>% 
                  mutate(zcta = GEOID,
                         race = if_else(id_part>5, 'Other Race alone', label),
                         mhhi = coalesce(estimate,0)) %>% 
                  mutate(mhhi_race_id = paste0(zcta, id_part)) %>% 
                  group_by(mhhi_race_id, zcta, race, id_part) %>% 
                  summarise(mhhi = mean(mhhi),
                            .groups = "drop") %>% 
                  ungroup() %>% 
                  arrange(zcta, id_part) %>% 
                  select(mhhi_race_id, zcta, race, mhhi)



```


### Population & MHHI by Race
```{r}

db_population_mhhi <- db_census_bureau_race %>% 
                          left_join(db_census_bureau_mhhi_race, by = c("zcta"="zcta","race"="race")) %>% 
                          select(-mhhi_race_id)

mhhi_summary <-  db_population_mhhi %>% filter(mhhi > 0) %>% 
                          group_by(race) %>% 
                          summarise(mhhi = sum(mhhi*population) / sum(population),
                                    population = sum(population),
                                    .groups = "drop"
                                    ) %>% ungroup %>% 
                          arrange(desc(mhhi))

mhhi_viz <- mhhi_summary %>% 
                mutate(race = fct_reorder(race, 1:6)) %>%
                ggplot(aes(race, mhhi, fill = race)) +
                geom_col() +
                scale_y_continuous(labels = scales::comma) +
                theme(axis.text.x = element_text(size = 12, angle = 45))

population_viz <- mhhi_summary %>% 
                mutate(race = fct_reorder(race, 1:6)) %>%
                ggplot(aes(race, population, fill = race)) +
                geom_col() +
                scale_y_continuous(labels = scales::comma) +
                theme(axis.text.x = element_text(size = 12, angle = 45))

ggplotly(mhhi_viz)
ggplotly(population_viz)

```


### Census Bureau Population Viz
```{r}

age_85203 <- db_census_bureau_population %>% filter(zcta == "85203") %>% 
              mutate(age_group = fct_reorder(age_group, 1:23)) %>%
              ggplot(aes(age_group, population, fill = age_group)) +
              geom_col() +
              scale_y_continuous(labels = scales::comma) +
              theme(axis.text.x = element_text(size = 12, angle = 45))

ggplotly(age_85203)

```



### Census Bureau Race
```{r}

race_population <- load_variables(2019, "acs5", cache = TRUE) %>% 
                        filter(substr(name ,1,7) == "B02001_" & 
                        name %notin% c("B02001_001"))

race_list <- race_population$name
df_race_pop <- as_tibble()

r <- "B02001_002"
for (r in race_list) {
  
  race_pop <- get_acs(geography = "zcta", year = 2019, survey = "acs5", 
                         variables = r)
  
  df_race_pop <- union_all(df_race_pop, race_pop)
  
}


race_mapping <- read_csv("race_mapping.csv")
db_census_bureau_race <- df_race_pop %>% left_join(race_mapping, by = c("variable"="name")) %>% 
                  mutate(zcta = GEOID,
                         race = if_else(id_part == 105,"Other Race alone",label),
                         population = estimate) %>% 
                  group_by(id_part, zcta, race) %>% 
                  summarise(
                            population = sum(population),
                            .groups = "drop"
                            ) %>% 
                  ungroup() %>% 
                  mutate(race_id = paste0(zcta, id_part)) %>% 
                  arrange(zcta, id_part) %>% 
                  select(race_id, zcta, race, population)


```


### Census Bureau Race Viz
```{r}

race_85203 <- db_census_bureau_race %>% filter(zcta == "85203") %>% 
              mutate(race = fct_reorder(race, 1:6)) %>%
              ggplot(aes(race, population, fill = race)) +
              scale_y_continuous(labels = scales::comma) +
              theme(axis.text.x = element_text(size = 12, angle = 45))

ggplotly(race_85203)



```

### COVID Data
```{r}
#county_list <- unique(db_geo_county_state_map$county_id)

db_covid <-  read_csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv") %>% 
                              arrange(date, fips) %>% 
                              mutate(
                                     covid_id = str_pad(row_number(), 10, pad = "0"),
                                     county_id = if_else(county == 'New York City' ,'36061',fips),
                                     deaths = if_else(is.na(deaths),0, deaths),
                                     cases = if_else(is.na(cases), 0, cases)
                                     ) %>% 
                              group_by(county_id) %>% 
                              mutate(
                                     cases = cases - coalesce(lag(cases, 1),0),
                                     deaths  = deaths - coalesce(lag(deaths, 1),0)
                                     ) %>% 
                              #filter(county_id %in% county_list) %>% 
                              select(covid_id, county_id, date, cases, deaths)



```


### Saving files down
```{r}

db_covid %>% write_tsv("database_csv/dc_covid.txt")
db_geo_county_state_map %>% write_csv("database_csv/dc_geo_county_state_map.csv")
db_census_bureau_income %>% write_csv("database_csv/dc_census_bureau_income.csv")
db_census_bureau_population %>% write_csv("database_csv/dc_census_bureau_population.csv")
db_census_bureau_race %>% write_csv("database_csv/dc_census_bureau_race.csv")

```


### Create new File.  Population and Household Median Income
```{r}

### Household Median Income Pull
hhincome_all <- as_tibble()
all_year <- 2011:2019

y <- 2019
for (y in all_year){
  hhincome <- get_acs(geography = "zcta", year = y, survey = "acs5",
                      variables = "B19013_001") %>% 
                      select(GEOID, NAME, estimate) %>% 
              mutate(
                census_id = paste0(y, substr(NAME,7,11)),
                year_census = y,
                date_census_start = as_date(paste0(y, "-01-01")),
                date_census_end = as_date(paste0(y,"-12-31")),
                zcta = substr(NAME,7,11),
                mhhi = estimate
              ) %>% 
              select(-GEOID, -estimate)
  
  hhincome_all <- union_all(hhincome_all, hhincome)
}


### Population

population_all <- as_tibble()
y <- 2019
for (y in all_year){
  hhincome <- get_acs(geography = "zcta", year = y, survey = "acs5",
                      variables = "B01003_001") %>% 
                      select(GEOID, NAME, estimate) %>% 
              mutate(
                census_id = paste0(y, substr(NAME,7,11)),
                year_census = y,
                date_census_start = as_date(paste0(y, "-01-01")),
                date_census_end = as_date(paste0(y,"-12-31")),
                zcta = substr(NAME,7,11),
                population = estimate
              ) %>% 
              select(-GEOID, -estimate)
  
  population_all <- union_all(population_all, population_census)
}




```

